config/routes.rb
Rails.application.routes.draw do
  resources :person

  root 'person#index'

end

app/models/lead.rb
class Lead 
	include ActiveModel::Model
    include ActiveModel::Validations

    attr_accessor :FirstName, :LastName, :Email, :Company, :Title, :Phone, :Website, :id

    validates :FirstName, :LastName, :Email, :Company, presence: true
    validates :Email,  format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
    validates :FirstName, :Phone, length: {maximum: 40}
    validates :LastName, :Email, length: {maximum: 80}
    validates :Title, length: {maximum: 128}
    validates :Website, :Company, length: {maximum: 255}

    def new_record?; false; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/person_controller.rb
require 'mct-rd-salesforce'

class PersonController < ApplicationController
	def index
		@leads = MctRdSalesforce::Lead.new.load(auth_params)
	end

	def show
	    @article = MctRdSalesforce::Lead.new.get(params[:id], auth_params)
	end

	def new
		@lead = Lead.new
	end

	def create
		lead = Lead.new(lead_params)

		@lead = lead

		if @lead.valid?
			MctRdSalesforce::Lead.new.create(auth_params, {
 				"name": lead.FirstName,
 				"lastName": lead.LastName,
 				"email": lead.Email,
 				"company": lead.Company,
 				"website": lead.Website,
 				"jobTitle": lead.Title,
 				"phone": lead.Phone,
 			})

			redirect_to root_path
		else
			render 'new' 		
		end
	end

	def edit
		lead = MctRdSalesforce::Lead.new.get(params[:id], auth_params)
		@leadId = lead.Id
		@lead = Lead.new(:id => lead.Id, :FirstName => lead.FirstName, :LastName => lead.LastName, :Email => lead.Email,
							:Company => lead.Company, :Website => lead.Website, :Title => lead.Title, :Phone => lead.Phone)
	end

	def update
		lead = Lead.new(lead_params)
	 	@lead = lead

		if @lead.valid?
			MctRdSalesforce::Lead.new.update(auth_params, {
				"id": params[:id],
				"name": lead.FirstName,
				"lastName": lead.LastName,
				"email": lead.Email,
				"company": lead.Company,
				"website": lead.Website,
				"jobTitle": lead.Title,
				"phone": lead.Phone,
			})

	    	redirect_to root_path
    	else
		 	@leadId = params[:id]
			render 'new' 	
		end
	end

	def destroy
		lead = MctRdSalesforce::Lead.new.destroy(params[:id], auth_params)
	 
		redirect_to root_path
	end

	private
		def auth_params
	    	{ "username" => "marcoscastrot@gmail.com", 
	    		"password" => "RdSale00", 
	    		"security_token" => "BEiWG5t5ksss9TYSsyKwX3AJ", 
	    		"client_id" => "3MVG9KI2HHAq33RzThySBJALGiShFAkW2FdKpRcLGv1HWskRFa4t_B6gusRM8bYvNAqenV21MHtsGa.ySEUNY", 
	    		"client_secret" => "3280416324043101337" 
	    	}
		end

	private
	  	def lead_params
	    	params.require(:lead).permit(:FirstName, :LastName, :Company, :Email, :Website, :Phone, :Title)
	  	end  	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MctRdSalesforceApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/person/edit.html.erb
<h1>Edit person</h1>
 
<%= form_for :lead, url: person_path(@leadId), method: :PUT do |f| %>
 
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@lead.errors.count, "error") %> Invalid fields:
      </h2>
      <ul>
        <% @lead.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :FirstName %><br>
    <%= f.text_field :FirstName %>
  </p>
 
  <p>
    <%= f.label :LastName %><br>
    <%= f.text_field :LastName %>
  </p>

  <p>
    <%= f.label :Company %><br>
    <%= f.text_field :Company %>
  </p>
 
  <p>
    <%= f.label :Email %><br>
    <%= f.text_field :Email %>
  </p>

  <p>
    <%= f.label :Website %><br>
    <%= f.text_field :Website %>
  </p>
 
  <p>
    <%= f.label :Phone %><br>
    <%= f.text_field :Phone %>
  </p>

  <p>
    <%= f.label :Title %><br>
    <%= f.text_field :Title %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', person_index_path %>

app/views/person/index.html.erb
<h1>List of people</h1>
<%= link_to 'New person', new_person_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Company</th>
    <th>Job Title</th>
    <th>Phone</th>
    <th>Website</th>
    <th colspan="3"></th>
  </tr>
 
  <% @leads.each do |lead| %>
    <tr>
      <td><%= lead.FirstName %> <%= lead.LastName %></td>
      <td><%= lead.Email %></td>
      <td><%= lead.Company %></td>
      <td><%= lead.Title %></td>
      <td><%= lead.Phone %></td>
      <td><%= lead.Website %></td>
      <td><%= link_to 'Show', person_path(lead.Id) %></td>
      <td><%= link_to 'Edit', edit_person_path(lead.Id) %></td>
      <td><%= link_to 'Destroy', person_path(lead.Id),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>

app/views/person/new.html.erb
<h1>New person</h1>

<%= form_for :lead, url: person_index_path do |f| %>
  
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@lead.errors.count, "error") %> Invalid fields:
      </h2>
      <ul>
        <% @lead.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :FirstName %><br>
    <%= f.text_field :FirstName %>
  </p>
 
  <p>
    <%= f.label :LastName %><br>
    <%= f.text_field :LastName %>
  </p>

  <p>
    <%= f.label :Company %><br>
    <%= f.text_field :Company %>
  </p>
 
  <p>
    <%= f.label :Email %><br>
    <%= f.text_field :Email %>
  </p>

  <p>
    <%= f.label :Website %><br>
    <%= f.text_field :Website %>
  </p>
 
  <p>
    <%= f.label :Phone %><br>
    <%= f.text_field :Phone %>
  </p>

  <p>
    <%= f.label :Title %><br>
    <%= f.text_field :Title %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', person_index_path %>

app/views/person/show.html.erb
<h1>Person</h1>

<p>
  <strong>First Name:</strong>
  <%= @article.FirstName %>
</p>
 
<p>
  <strong>Last Name:</strong>
  <%= @article.LastName %>
</p>

<p>
  <strong>Company:</strong>
  <%= @article.Company %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @article.Email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @article.Website %>
</p>
 
<p>
  <strong>Phone:</strong>
  <%= @article.Phone %>
</p>

<p>
  <strong>Title:</strong>
  <%= @article.Title %>
</p>

<%= link_to 'Back', person_index_path %>